"""Tests for hooks/pre-strip-llm-attribution.sh — BLOCKS gh pr create with LLM attribution.

Anchor: header comment. Coverage of Copilot/etc. is via generalized patterns,
so we assert on those generalized shapes, not vendor literals.
"""
from conftest import hook_stdin, run_hook

import pytest

# (id, body_fragment, expect_block) — all wrapped in `gh pr create --body '...'`
ATTR_CASES = [
    ("claude-code", "Generated with [Claude Code]", True),
    ("claude-prefix", "Generated with [Claude Stuff]", True),
    ("robot-emoji-generated-with", "🤖 Generated with Foo", True),
    ("coauthor-anthropic", "Co-Authored-By: X <noreply@anthropic.com>", True),
    ("coauthor-github", "Co-Authored-By: X <noreply@github.com>", True),
    ("generated-by-name-code", "Generated by Cursor Code", True),
    ("robot-anything-generated", "🤖 something Generated here", True),
    ("html-generated-comment", "<!-- generated by bot -->", True),
    ("clean-body", "just a normal PR description", False),
]


@pytest.mark.parametrize(
    "body,expect_block",
    [(c[1], c[2]) for c in ATTR_CASES],
    ids=[c[0] for c in ATTR_CASES],
)
def test_attribution_detection(body, expect_block):
    res = run_hook(
        "pre-strip-llm-attribution.sh",
        hook_stdin("Bash", command=f"gh pr create --body '{body}'"),
    )
    if expect_block:
        assert res.blocked, f"expected block\n{res.stderr}"
    else:
        assert res.allowed, f"expected allow\n{res.stderr}"


def test_non_pr_command_with_attribution_allowed():
    # attribution string inside a non-`gh pr create` command is not blocked
    res = run_hook(
        "pre-strip-llm-attribution.sh",
        hook_stdin("Bash", command='echo "Generated with [Claude Code]"'),
    )
    assert res.allowed


def test_gh_other_subcommand_allowed():
    res = run_hook(
        "pre-strip-llm-attribution.sh",
        hook_stdin("Bash", command="gh pr list"),
    )
    assert res.allowed


def test_empty_command_allowed():
    res = run_hook(
        "pre-strip-llm-attribution.sh",
        hook_stdin("Bash", command=""),
    )
    assert res.allowed
