#!/usr/bin/env bash
# Trigger:  PreToolUse — matcher: Bash
# Behavior: BLOCKS `gh pr create` commands that contain LLM attribution
#           markers (Claude Code, GitHub Copilot, etc.) in the PR body.
#           Coverage of Copilot/etc. is via generalized patterns
#           (e.g. "Generated by <Name> Code", "🤖...Generated"), not vendor literals.
# Disable:  chmod -x hooks/pre-strip-llm-attribution.sh

set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib/utils.sh"

INPUT=$(cat)
CMD=$(json_get "$INPUT" "tool_input.command")

[[ -z "$CMD" ]] && exit 0

# Only inspect commands that invoke gh pr create.
FIRST_LINE=$(printf '%s' "$CMD" | head -1)
if ! echo "$FIRST_LINE" | grep -qE '(^|[;&|]\s*)gh\s+pr\s+create\b'; then
    exit 0
fi

# Known LLM attribution patterns — one per -e flag.
# Covers Claude Code (current and future versions), GitHub Copilot, Cursor,
# and generic "Generated with/by" markers with robot emoji.
if printf '%s' "$CMD" | grep -qE \
    'Generated with \[Claude Code\]'\
    '|Generated with \[Claude'\
    '|🤖 Generated with'\
    '|Co-Authored-By:.*<(noreply|no-reply)@anthropic\.com>'\
    '|Co-Authored-By:.*<noreply@github\.com>'\
    '|Generated by [A-Z][a-zA-Z]+ Code'\
    '|🤖.*Generated'\
    '|<!-- generated by'; then
    log_block "LLM attribution detected in gh pr create body. Remove the attribution line and retry."
    exit 2
fi

exit 0
